from sqlalchemy import Boolean, Column, ForeignKey, Integer, String
from sqlalchemy.orm import relationship

from ..db.base_class import KBase


class VocList(KBase):
    __tablename__ = "dashboard_voc_list"

    lte_only              = Column(String(2000))
    hndset_pet_nm         = Column(String(2000))
    aed_div_itg_cd        = Column(String(2000))
    sa_5g_suprt_div_nm    = Column(String(2000))
    voc_wjt_prmr_sorc_id  = Column(String(2000))
    voc_wjt_prmr_nm       = Column(String(2000))
    voc_wjt_scnd_sorc_id  = Column(String(2000))
    voc_wjt_scnd_nm       = Column(String(2000))
    voc_wjt_tert_sorc_id  = Column(String(2000))
    voc_wjt_tert_nm       = Column(String(2000))
    voc_wjt_qrtc_sorc_id  = Column(String(2000))
    voc_wjt_qrtc_nm       = Column(String(2000))
    voc_type_itg_cd       = Column(String(2000))
    voc_type_nm           = Column(String(2000))
    sr_tt_rcp_no          = Column(String(2000), primary_key=True)
    custcol_56            = Column(String(2000))
    volte_out_cmplt_yn    = Column(String(2000))
    equip_cd              = Column(String(2000))
    bprod_sbt_id_m        = Column(String(2000))
    bprod_nm              = Column(String(2000))
    custcol_70            = Column(String(2000))
    base_ym               = Column(String(2000))
    base_date             = Column(String(2000))
    bts_biz_hq_cd         = Column(String(2000))
    bts_biz_hq_nm         = Column(String(2000))
    hndset_model_sbt_id   = Column(String(2000))
    hndset_model_nm       = Column(String(2000))
    band_nm               = Column(String(2000))
    anals_5_prod_level_id = Column(String(2000))
    anals_5_prod_level_nm = Column(String(2000))
    custcol_57            = Column(String(2000))
    svc_cont_id           = Column(String(2000))
    sbt_bts_cd            = Column(String(2000))
    gun_gu_nm             = Column(String(2000))
    sido_nm               = Column(String(2000))
    pricng_div_5_lvl      = Column(String(2000))
    oper_team_cd          = Column(String(2000))
    bts_oper_team_nm      = Column(String(2000))
    eup_myun_dong_nm      = Column(String(2000))
    trobl_rgn_adr_sbst    = Column(String(2000))
    trobl_rgn_dtl_sbst    = Column(String(2000))
    equip_cd0             = Column(String(2000))
    adm_cd                = Column(String(2000))
    adm_cd0               = Column(String(2000))
    adm_cd1               = Column(String(2000))
    adm_cd2               = Column(String(2000))
    wjxbfs1               = Column(String(2000))